### ISSUE TITLE
Feature#01 (Modificar coordenadas)

### ISSUE THREAD

**Issue by jacobocl** [jacobocl/IWVG.SwC.JacoboConejoLima#1]
Dar la posibilidad de **modificar las coordenadas** en la clase `Point`.
[Más información...](https://github.com/jacobocl/IWVG.SwC.JacoboConejoLima/wiki/Trabajo-a-realizar#feature01-modificar-coordenadas)

**Comment by javier917** [comment]
Creados los métodos para cambiar coordenadas

**Comment by jacobocl** [comment]
Todo bien 👍🏼
