### ISSUE TITLE
Feature#02 (Nombre en mayúsculas)

### ISSUE THREAD

**Issue by jacobocl** [jacobocl/IWVG.SwC.JacoboConejoLima#2]
Modificación de la clase `User` para que permita obtener el **nombre completo en mayúsculas**.

[Más información...](https://github.com/jacobocl/IWVG.SwC.JacoboConejoLima/wiki/Trabajo-a-realizar#feature02-nombre-en-may%C3%BAsculas)

**Comment by JorgeCoke** [comment]
User:fullNameUppercase Done 👍🏼

**Comment by jacobocl** [comment]
Todo correcto 👍🏼
