### ISSUE TITLE
Feature#03 (Calcular la media)

### ISSUE THREAD

**Issue by jacobocl** [jacobocl/IWVG.SwC.JacoboConejoLima#3]
Crear un método que calcule la **media** en `DecimalCollection`.

[Más información](https://github.com/jacobocl/IWVG.SwC.JacoboConejoLima/wiki/Trabajo-a-realizar#feature03-calcular-la-media)

**Comment by thomasklz** [comment]
Feature#03 realizada.

**Comment by jacobocl** [comment]
Todo correcto :ok_hand:.
