### ISSUE TITLE
Feature#04 (Multiplicar)

### ISSUE THREAD

**Issue by jacobocl** [jacobocl/IWVG.SwC.JacoboConejoLima#4]
Crear un método para **multiplicar** fracciones en la clase `Fraction`.

[Más información...](https://github.com/jacobocl/IWVG.SwC.JacoboConejoLima/wiki/Trabajo-a-realizar#feature04-multiplicar)

**Comment by javier917** [comment]
Creado el método multilplicar

**Comment by jacobocl** [comment]
Correctamente implementado :clap:
