### ISSUE TITLE
Feature#06 (Menor)

### ISSUE THREAD

**Issue by jacobocl** [jacobocl/IWVG.SwC.JacoboConejoLima#6]
Crear un método en la clase `Fraction` que indique si otra fracción es **menor** o no.

[Más información...](https://github.com/jacobocl/IWVG.SwC.JacoboConejoLima/wiki/Trabajo-a-realizar#feature06-menor)

**Comment by thomasklz** [comment]
Feature#06 - Terminada

**Comment by jacobocl** [comment]
Perfecto.
